name: .NET CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'GameOfLife.csharp/**'
      - '.github/workflows/dotnet-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'GameOfLife.csharp/**'
      - '.github/workflows/dotnet-ci.yml'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
      DOTNET_NOLOGO: 'true'
    defaults:
      run:
        working-directory: GameOfLife.csharp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK (with NuGet cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: |
            GameOfLife.csharp/**/*.csproj
            GameOfLife.csharp/**/packages.lock.json

      - name: Restore
        run: dotnet restore Life.sln

      - name: Build (treat warnings as errors)
        run: dotnet build Life.sln --configuration Release --no-restore -warnaserror

      # install dotnet-format (code style)
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Format check
        run: dotnet format --verify-no-changes
        # continue-on-error: true   # uncomment to allow PRs with formatting issues

      - name: Test (with trx + coverage)
        run: >
          dotnet test tests/Life.Api.Tests/Life.Api.Tests.csproj
          --configuration Release
          --no-build
          --logger "trx;LogFileName=test-results.trx"
          --collect "XPlat Code Coverage"

      - name: List TestResults
        if: always()
        run: |
          echo "Looking for TestResults under $(pwd)"
          find . -path "*/TestResults/*" -type f -print || true

      - name: Install reportgenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH (reportgenerator)
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      # Generate coverage report only if coverage files exist
      - name: Generate coverage report (text + HTML)
        if: always()
        shell: bash
        run: |
          shopt -s globstar nullglob
          files=( **/TestResults/**/coverage.cobertura.xml )
          if [ ${#files[@]} -eq 0 ]; then
            echo "No coverage.cobertura.xml found; skipping reportgenerator."
            mkdir -p coverage-report
            exit 0
          fi
          reportgenerator \
            -reports:**/TestResults/**/coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:TextSummary;HtmlInline_AzurePipelines

      # Upload test results (won’t fail if nothing to upload)
      - name: Upload test results (trx + coverage)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/**/coverage.cobertura.xml

      # Upload coverage HTML (won’t fail if folder is empty/missing)
      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage-report

      - name: Post coverage summary to job log
        if: always()
        run: |
          if [ -f coverage-report/Summary.txt ]; then
            cat coverage-report/Summary.txt
          else
            echo "No coverage summary generated."
          fi
